server:
  port: 9003

spring:
  application:
    name: cloud-sink
  cloud:
    function:
      definition: nameSink
    stream:
      bindings:
        nameSink-in-0:
          destination: sink-input
          group: ${spring.application.name:sink}

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s