server:
  port: 9002

spring:
  application:
    name: cloud-processor
  cloud:
    function:
      definition: processName
    stream:
      bindings:
        processName-in-0:
          destination: processor-input
          group: ${spring.application.name:processor}
        processName-out-0:
          destination: sink-input


  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s
